"""Report rendering: Markdown, JSON, and SARIF.

SARIF is included because it is what GitHub code scanning ingests: point the
workflow at ``findings.sarif`` and drift shows up in the Security tab of the
repository, with history, rather than only in a job log nobody reads.
"""

from __future__ import annotations

import json
from typing import Any

from .models import FindingKind, ScanReport, Severity

_SEVERITY_EMOJI = {
    Severity.CRITICAL: "🔴",
    Severity.HIGH: "🟠",
    Severity.MEDIUM: "🟡",
    Severity.LOW: "🔵",
    Severity.INFO: "⚪",
}

# SARIF only has error/warning/note/none, so several severities collapse.
_SARIF_LEVEL = {
    Severity.CRITICAL: "error",
    Severity.HIGH: "error",
    Severity.MEDIUM: "warning",
    Severity.LOW: "note",
    Severity.INFO: "note",
}

_SARIF_RANK = {
    Severity.CRITICAL: 95.0,
    Severity.HIGH: 80.0,
    Severity.MEDIUM: 55.0,
    Severity.LOW: 30.0,
    Severity.INFO: 5.0,
}


def render_markdown(report: ScanReport, *, include_info: bool = True) -> str:
    """Render a human-readable report."""
    lines: list[str] = []
    counts = report.counts_by_severity()
    findings = [f for f in report.findings if include_info or f.severity > Severity.INFO]

    lines.append("# dnsdrift report")
    lines.append("")
    lines.append(f"- **Scanned:** {len(report.snapshots)} domain(s)")
    lines.append(f"- **Started:** {report.started_at}")
    lines.append(f"- **Finished:** {report.finished_at}")
    lines.append(
        "- **Baseline:** "
        + (
            "compared against previous scan"
            if report.baseline_available
            else "none — this run establishes the baseline, so no drift findings are possible"
        )
    )
    lines.append("")
    lines.append(
        "| Critical | High | Medium | Low | Info |\n|---:|---:|---:|---:|---:|\n"
        f"| {counts['critical']} | {counts['high']} | {counts['medium']} "
        f"| {counts['low']} | {counts['info']} |"
    )
    lines.append("")

    if report.ai_summary:
        lines.append("## Summary")
        lines.append("")
        lines.append(report.ai_summary.strip())
        lines.append("")
        lines.append(
            "> _Generated by a language model from the findings below. Advisory only — "
            "the findings themselves are produced deterministically._"
        )
        lines.append("")

    drift = [f for f in findings if f.kind is FindingKind.DRIFT]
    posture = [f for f in findings if f.kind is FindingKind.POSTURE]
    operational = [f for f in findings if f.kind is FindingKind.OPERATIONAL]

    if drift:
        lines.append(f"## Changes since last scan ({len(drift)})")
        lines.append("")
        lines.extend(_render_findings(drift))

    if posture:
        lines.append(f"## Current posture ({len(posture)})")
        lines.append("")
        lines.extend(_render_findings(posture))

    if operational:
        lines.append(f"## Scan issues ({len(operational)})")
        lines.append("")
        lines.extend(_render_findings(operational))

    if not findings:
        lines.append("No findings. Every configured check passed.")
        lines.append("")

    lines.append("---")
    lines.append(f"_dnsdrift {report.tool_version}_")
    lines.append("")
    return "\n".join(lines)


def _render_findings(findings: list[Any]) -> list[str]:
    lines: list[str] = []
    current_domain: str | None = None
    for finding in findings:
        if finding.domain != current_domain:
            current_domain = finding.domain
            lines.append(f"### `{current_domain}`")
            lines.append("")
        emoji = _SEVERITY_EMOJI[finding.severity]
        lines.append(f"{emoji} **{finding.severity.value.upper()} — {finding.title}**  ")
        lines.append(f"`{finding.check}` · {finding.detail}")
        if finding.remediation:
            lines.append("")
            lines.append(f"> **Fix:** {finding.remediation}")
        if finding.references:
            lines.append("")
            lines.append("> " + " · ".join(f"[ref]({r})" for r in finding.references))
        lines.append("")
    return lines


def render_json(report: ScanReport) -> str:
    return report.to_json()


def render_sarif(report: ScanReport) -> str:
    """Render SARIF 2.1.0 for GitHub code scanning."""
    rules: dict[str, dict[str, Any]] = {}
    results: list[dict[str, Any]] = []

    for finding in report.findings:
        rule_id = f"dnsdrift/{finding.check}/{finding.kind.value}"
        if rule_id not in rules:
            rules[rule_id] = {
                "id": rule_id,
                "name": f"{finding.check}-{finding.kind.value}",
                "shortDescription": {"text": f"{finding.check} {finding.kind.value} finding"},
                "fullDescription": {
                    "text": f"dnsdrift {finding.kind.value} findings produced by the {finding.check} check."
                },
                "defaultConfiguration": {"level": _SARIF_LEVEL[finding.severity]},
                "properties": {"tags": ["security", "dns", finding.check]},
            }

        results.append(
            {
                "ruleId": rule_id,
                "level": _SARIF_LEVEL[finding.severity],
                "rank": _SARIF_RANK[finding.severity],
                "message": {
                    "text": f"{finding.domain}: {finding.title}. {finding.detail}"
                    + (f" Fix: {finding.remediation}" if finding.remediation else "")
                },
                "partialFingerprints": {"dnsdriftFingerprint": finding.fingerprint},
                "properties": {
                    "domain": finding.domain,
                    "check": finding.check,
                    "kind": finding.kind.value,
                    "severity": finding.severity.value,
                },
                "locations": [
                    {
                        "physicalLocation": {
                            # SARIF requires a location. There is no source file
                            # for a DNS finding, so the domain is encoded as a
                            # synthetic URI — GitHub renders this readably and
                            # groups findings per domain.
                            "artifactLocation": {"uri": f"domains/{finding.domain}"},
                            "region": {"startLine": 1},
                        }
                    }
                ],
            }
        )

    document = {
        "$schema": "https://json.schemastore.org/sarif-2.1.0.json",
        "version": "2.1.0",
        "runs": [
            {
                "tool": {
                    "driver": {
                        "name": "dnsdrift",
                        "version": report.tool_version,
                        "informationUri": "https://github.com/angeldeleon/dnsdrift",
                        "rules": list(rules.values()),
                    }
                },
                "results": results,
            }
        ],
    }
    return json.dumps(document, indent=2)


def render(report: ScanReport, fmt: str, *, include_info: bool = True) -> str:
    renderers = {
        "markdown": lambda: render_markdown(report, include_info=include_info),
        "md": lambda: render_markdown(report, include_info=include_info),
        "json": lambda: render_json(report),
        "sarif": lambda: render_sarif(report),
    }
    try:
        return renderers[fmt.lower()]()
    except KeyError as exc:
        raise ValueError(f"unknown output format {fmt!r} (expected: markdown, json, sarif)") from exc
